// Centralized icon exports to improve tree-shaking and reduce chunk splitting
// This helps prevent the ERR_INSUFFICIENT_RESOURCES error with @tabler/icons-react

// Common UI Icons
export {
  IconSettings,
  IconUser,
  IconUsers,
  IconUserPlus,
  IconUserCircle,
  IconMoon,
  IconSun,
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconX,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronDown,
  IconArrowLeft,
  IconSearch,
  IconFilter,
  IconSend,
  IconCopy,
  IconShare,
  IconDownload,
  IconUpload,
  IconRefresh,
  IconLoader,
  IconAlertTriangle,
  IconInfoCircle,
  IconEye,
  IconEyeOff,
  IconLock,
  IconShield,
  IconBell,
  IconNotification,
  IconPalette,
  IconDeviceLaptop,
  IconLogout,
  IconCamera,
} from "@tabler/icons-react";

// Business Domain Icons
export {
  IconGasStation,
  IconTank,
  IconTruck,
  IconBuildingFactory,
  IconCash,
  IconCoin,
  IconCurrencyDollar,
  IconReceipt,
  IconReport,
  IconChartLine,
  IconChartBar,
  IconDatabase,
  IconCalendar,
  IconClock,
  IconBuilding,
  IconMapPin,
  IconPhone,
  IconMail,
} from "@tabler/icons-react";

// Export the Icon type for TypeScript
export type { Icon } from "@tabler/icons-react"; 