@echo off
echo Starting thorough cleanup...

echo Cleaning Vite cache...
rmdir /s /q "node_modules\.vite" 2>nul

echo Cleaning package manager cache...
npm cache clean --force

echo Cleanup complete.
echo Starting optimized application...
npm run dev 