@echo off
echo Testing optimized React application startup...
echo.
echo Cleaning caches...
rmdir /s /q "node_modules\.vite" 2>nul
echo.
echo Starting development server...
echo Please wait, this may take a moment...
echo.
npm run dev 